#!/usr/bin/env bash

if ! type yad  >/dev/null; then
  echo 'error: need yad to gui' >&2
  exit 1
fi

if [[ -z "$1" ]]; then
  echo 'error: no file'
  exit 1
fi

str_file="$1"
str_txt=$(awk -f format.awk "$str_file")

# Clipboard line on click time cell
clipboard() {
  local line=$(sed -E "s/^'([[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2})' '(.+)'$/\1 = \2/g" <<< "$1")
  printf "%s" "$line" | xclip -selection clipboard
}
export -f clipboard

# Show yad
yad --list \
  --title=Transcrição \
  --editable --editable-cols=2 \
  --search-column=2 \
  --regex-search \
  --dclick-action='bash -c "clipboard \"%s\""' \
  --column=Tempo --column=Frase \
  < <(awk -F ' = ' '{ print $1 "\n" $2 }' <<< $str_txt)
