#!/usr/bin/env bash

# Youtube download transcript

set -e

cwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
lang=pt

# Check yt-dlp
if ! type yt-dlp >/dev/null; then
  echo 'error: need yt-dlp' >&2
  exit 1
fi

# Check url
if [[ $1 ]]; then
  url="$1"
else
  echo 'error: need url' >&2
  exit 1
fi

# Get video title
title=$(yt-dlp \
  --restrict-filenames \
  --print filename \
  -o "%(title).20s" "$url" 2>/dev/null
)

# Check title
if [[ -z "$title" ]]; then
  echo 'error: could not get video title' >&2
  exit 1
fi

srt_file="$title.$lang.srt"
txt_file="$title.txt"

# Check file exist
if [[ -f "$srt_file" ]]; then
  read -rp 'File exist overwrie [y/N]: ' opc
  if [[ $opc =~ [Yy] ]]; then
    str_file_overwrite=true
  fi
fi

# Get transcript
if [[ ! -f "$srt_file" ]] || [[ $srt_file_overwrite == 'true' ]]; then
  yt-dlp \
    --skip-download \
    --sub-format srt \
    --sub-lang $lang \
    --write-subs \
    --write-auto-subs \
    --quiet \
    --no-warnings \
    --progress-template "Downloading: %(progress._percent_str)s" \
    --js-runtimes node \
    --remote-components ejs:github \
    --output "$title" \
    "$url"
fi

# Convert srt in dosini format
awk -f "$cwd/format.awk" "$srt_file" > "$txt_file"

# Read a option
read -rp '
p) Print
o) Open
g) Gui
q) Quit

Option: ' opc

case "$opc" in
  p) echo "$srt_txt" ;;
  o) $EDITOR "$txt_file" ;;
  g) $cwd/gui "$srt_file" ;;
  q) exit 0 ;;
esac
